/* This file was automatically generated on Tue 19 Jan 2021 14:50:36 GMT from
 * source: /dls_sw/work/R3.14.12.7/support/ajf67/EPICSExercises/ADTraining/etc/makeIocs/exUser1.xml
 * 
 * *** Please do not edit this file: edit the source file instead. ***
 *  */
#include "epicsExit.h"
#include "epicsThread.h"
#include "iocsh.h"

int main(int argc, char *argv[])
{
    if(argc>=2) {
        iocsh(argv[1]);
        epicsThreadSleep(.2);
    }
    iocsh(NULL);
    epicsExit(0);
    return 0;
}

